---
title: "Assignment 5"
author: "Prithvi Abhishetty"
date: "2022-11-21"
output: html_document # you can change to other output format if you want
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 1. Conditional probability, Bayes rule and independence

## 1.1 (Q1)
```{r}
p_A<-0.9
p_B_given_A<-0.8
p_not_B_given_not_A<-0.75
p_B<-p_B_given_A*p_A+(1-p_not_B_given_not_A)*(1-p_A)
p_A_given_B<-p_B_given_A*p_A/p_B
p_A_given_B

```


....

# 2. Random variables and discrete random variables


....


## 2.2 (Q1)

....

## 2.2 (Q4)

```{r}
samples_Xi <- rmultinom(2, 7, prob=c(0.5, 0.2, 0.3))
samples_Y = data.frame(Y=0*samples_Xi[1,] + 3*samples_Xi[2,] + 10*samples_Xi[3,])
samples_Xi
head(samples_Y)
```
```{r}
samples_Xi <- rmultinom(50000, 3, c(0.5, 0.2, 0.3) )
samples_Y = data.frame(Y=0*samples_Xi[1,] + 3*samples_Xi[2,] + 10*samples_Xi[3,])
head(samples_Y)
```
```{r}
ggplot(samples_Y, aes(Y)) + geom_bar() + theme_bw()
```
```{r}
samples_Xi <- rmultinom(50000, 25, c(0.5, 0.2, 0.3) )
samples_Y = data.frame(Y=0*samples_Xi[1,] + 3*samples_Xi[2,] + 10*samples_Xi[3,])
head(samples_Y)
ggplot(samples_Y, aes(Y)) + geom_bar() + theme_bw()
print(range(samples_Y))
print(diff(range(samples_Y)))
```
```{r}
samples_Xi <- rmultinom(50000, 2000, c(0.5, 0.2, 0.3) )
samples_Y = data.frame(Y=0*samples_Xi[1,] + 3*samples_Xi[2,] + 10*samples_Xi[3,])
head(samples_Y)
ggplot(samples_Y, aes(Y)) + geom_bar() + theme_bw()
```





